# Generated by Django 2.2.4 on 2019-10-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='visited',
            field=models.IntegerField(default=0),
        ),
    ]
